name: l100km
description: Statistika spořeby
version: 0.0.1

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  angular2: '^3.0.0'
  angular_components: '^0.5.0'
  googleapis_auth: "^0.2.3"
  googleapis: "^0.38.0"
  intl: "^0.15.0"
  usage: "^3.0.0"
  
dev_dependencies:
  browser:
  dart_to_js_script_rewriter:

transformers:
  - angular2:
      platform_directives:
      - 'package:angular2/common.dart#COMMON_DIRECTIVES'
      platform_pipes:
      - 'package:angular2/common.dart#COMMON_PIPES'
      entry_points: web/main.dart
  - dart_to_js_script_rewriter
