name: l100km
description: Statistika spořeby
version: 0.0.1

environment:
  sdk: '>=1.23.0-dev.11.7'

dependencies:
  angular2: '>=3.0.0-beta'
  angular2_components: '>=0.4.0-alpha'
  googleapis_auth:
  googleapis:
  intl:
  
dev_dependencies:
  browser:
  dart_to_js_script_rewriter:

transformers:
  - angular2:
      platform_directives:
      - 'package:angular2/common.dart#COMMON_DIRECTIVES'
      platform_pipes:
      - 'package:angular2/common.dart#COMMON_PIPES'
      entry_points: web/main.dart
  - dart_to_js_script_rewriter
